name: Build and Push Image Mlti Extensions
on:
  push:
    paths:
      - 'Dockerfile_multi'
      - 'init.go'
      - 'settings.json'
    branches:
      - main
  schedule:
    - cron:  '0 6 * * 2'
  # have the ability to trigger this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v3

    - name: Free Space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/lib/android
        rm -rf /opt/hostedtoolcache/Java*
        rm -rf /opt/hostedtoolcache/Ruby*
        rm -rf /opt/hostedtoolcache/Go*
        rm -rf /opt/hostedtoolcache/node*

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: selenium-vscode-multi
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile_multi

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/${{ secrets.REGESTRY_NAME }}
        username: ${{ secrets.REGESTRY_USER_NAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Print image url
      run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
